language: node_js
node_js:
  - lts/*
sudo: false
cache:
  yarn: true
  directories:
    - 'node_modules'
env:
  CI=true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: lint
      script: yarn lint
